[project]
name = "mortgage-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
]
